version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-todo_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-todo_pass}
      - POSTGRES_DB=${POSTGRES_DB:-todo_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER:-todo_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-todo_pass}
      - POSTGRES_DB=${POSTGRES_DB:-todo_app}
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
