version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-todo_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-todo_pass}
      - POSTGRES_DB=${POSTGRES_DB:-todo_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  app:
    image: ${REGISTRY:-localhost}/todo-app:${TAG:-latest}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER:-todo_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-todo_pass}
      - POSTGRES_DB=${POSTGRES_DB:-todo_app}
      - REDIS_URL=redis://redis:6379
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: overlay
